"""Quick Draw category list and the curated pool used for random class draws.

ALL_CATEGORIES is the full set of 345 Quick Draw dataset categories (from
https://github.com/googlecreativelab/quickdraw-dataset categories.txt, fetched
2026-09-08). EXCLUDED_CATEGORIES removes categories that are pure geometric
primitives, abstract concepts/patterns rather than drawable objects, abstract
multi-object scenes, or body-part fragments that are hard to tell apart as simple
outlines - curated with the user so CATEGORY_POOL stays recognizable and fun to
draw for a walk-up general-public kiosk. Tune the pool by editing EXCLUDED_CATEGORIES,
not by hand-editing ALL_CATEGORIES.
"""

ALL_CATEGORIES: list[str] = [
    'aircraft carrier',
    'airplane',
    'alarm clock',
    'ambulance',
    'angel',
    'animal migration',
    'ant',
    'anvil',
    'apple',
    'arm',
    'asparagus',
    'axe',
    'backpack',
    'banana',
    'bandage',
    'barn',
    'baseball',
    'baseball bat',
    'basket',
    'basketball',
    'bat',
    'bathtub',
    'beach',
    'bear',
    'beard',
    'bed',
    'bee',
    'belt',
    'bench',
    'bicycle',
    'binoculars',
    'bird',
    'birthday cake',
    'blackberry',
    'blueberry',
    'book',
    'boomerang',
    'bottlecap',
    'bowtie',
    'bracelet',
    'brain',
    'bread',
    'bridge',
    'broccoli',
    'broom',
    'bucket',
    'bulldozer',
    'bus',
    'bush',
    'butterfly',
    'cactus',
    'cake',
    'calculator',
    'calendar',
    'camel',
    'camera',
    'camouflage',
    'campfire',
    'candle',
    'cannon',
    'canoe',
    'car',
    'carrot',
    'castle',
    'cat',
    'ceiling fan',
    'cello',
    'cell phone',
    'chair',
    'chandelier',
    'church',
    'circle',
    'clarinet',
    'clock',
    'cloud',
    'coffee cup',
    'compass',
    'computer',
    'cookie',
    'cooler',
    'couch',
    'cow',
    'crab',
    'crayon',
    'crocodile',
    'crown',
    'cruise ship',
    'cup',
    'diamond',
    'dishwasher',
    'diving board',
    'dog',
    'dolphin',
    'donut',
    'door',
    'dragon',
    'dresser',
    'drill',
    'drums',
    'duck',
    'dumbbell',
    'ear',
    'elbow',
    'elephant',
    'envelope',
    'eraser',
    'eye',
    'eyeglasses',
    'face',
    'fan',
    'feather',
    'fence',
    'finger',
    'fire hydrant',
    'fireplace',
    'firetruck',
    'fish',
    'flamingo',
    'flashlight',
    'flip flops',
    'floor lamp',
    'flower',
    'flying saucer',
    'foot',
    'fork',
    'frog',
    'frying pan',
    'garden',
    'garden hose',
    'giraffe',
    'goatee',
    'golf club',
    'grapes',
    'grass',
    'guitar',
    'hamburger',
    'hammer',
    'hand',
    'harp',
    'hat',
    'headphones',
    'hedgehog',
    'helicopter',
    'helmet',
    'hexagon',
    'hockey puck',
    'hockey stick',
    'horse',
    'hospital',
    'hot air balloon',
    'hot dog',
    'hot tub',
    'hourglass',
    'house',
    'house plant',
    'hurricane',
    'ice cream',
    'jacket',
    'jail',
    'kangaroo',
    'key',
    'keyboard',
    'knee',
    'knife',
    'ladder',
    'lantern',
    'laptop',
    'leaf',
    'leg',
    'light bulb',
    'lighter',
    'lighthouse',
    'lightning',
    'line',
    'lion',
    'lipstick',
    'lobster',
    'lollipop',
    'mailbox',
    'map',
    'marker',
    'matches',
    'megaphone',
    'mermaid',
    'microphone',
    'microwave',
    'monkey',
    'moon',
    'mosquito',
    'motorbike',
    'mountain',
    'mouse',
    'moustache',
    'mouth',
    'mug',
    'mushroom',
    'nail',
    'necklace',
    'nose',
    'ocean',
    'octagon',
    'octopus',
    'onion',
    'oven',
    'owl',
    'paintbrush',
    'paint can',
    'palm tree',
    'panda',
    'pants',
    'paper clip',
    'parachute',
    'parrot',
    'passport',
    'peanut',
    'pear',
    'peas',
    'pencil',
    'penguin',
    'piano',
    'pickup truck',
    'picture frame',
    'pig',
    'pillow',
    'pineapple',
    'pizza',
    'pliers',
    'police car',
    'pond',
    'pool',
    'popsicle',
    'postcard',
    'potato',
    'power outlet',
    'purse',
    'rabbit',
    'raccoon',
    'radio',
    'rain',
    'rainbow',
    'rake',
    'remote control',
    'rhinoceros',
    'rifle',
    'river',
    'roller coaster',
    'rollerskates',
    'sailboat',
    'sandwich',
    'saw',
    'saxophone',
    'school bus',
    'scissors',
    'scorpion',
    'screwdriver',
    'sea turtle',
    'see saw',
    'shark',
    'sheep',
    'shoe',
    'shorts',
    'shovel',
    'sink',
    'skateboard',
    'skull',
    'skyscraper',
    'sleeping bag',
    'smiley face',
    'snail',
    'snake',
    'snorkel',
    'snowflake',
    'snowman',
    'soccer ball',
    'sock',
    'speedboat',
    'spider',
    'spoon',
    'spreadsheet',
    'square',
    'squiggle',
    'squirrel',
    'stairs',
    'star',
    'steak',
    'stereo',
    'stethoscope',
    'stitches',
    'stop sign',
    'stove',
    'strawberry',
    'streetlight',
    'string bean',
    'submarine',
    'suitcase',
    'sun',
    'swan',
    'sweater',
    'swing set',
    'sword',
    'syringe',
    'table',
    'teapot',
    'teddy-bear',
    'telephone',
    'television',
    'tennis racquet',
    'tent',
    'The Eiffel Tower',
    'The Great Wall of China',
    'The Mona Lisa',
    'tiger',
    'toaster',
    'toe',
    'toilet',
    'tooth',
    'toothbrush',
    'toothpaste',
    'tornado',
    'tractor',
    'traffic light',
    'train',
    'tree',
    'triangle',
    'trombone',
    'truck',
    'trumpet',
    't-shirt',
    'umbrella',
    'underwear',
    'van',
    'vase',
    'violin',
    'washing machine',
    'watermelon',
    'waterslide',
    'whale',
    'wheel',
    'windmill',
    'wine bottle',
    'wine glass',
    'wristwatch',
    'yoga',
    'zebra',
    'zigzag',
]

EXCLUDED_CATEGORIES: frozenset[str] = frozenset({
    'animal migration',
    'beach',
    'beard',
    'camouflage',
    'circle',
    'elbow',
    'garden',
    'goatee',
    'hexagon',
    'hurricane',
    'knee',
    'line',
    'moustache',
    'ocean',
    'octagon',
    'pond',
    'rain',
    'river',
    'spreadsheet',
    'square',
    'squiggle',
    'toe',
    'triangle',
    'zigzag',
})

CATEGORY_POOL: list[str] = [c for c in ALL_CATEGORIES if c not in EXCLUDED_CATEGORIES]

